export const languagePT = {
  welcome_welcome: 'Bem vindo',
  welcome_questions_actions: 'cadastrar/ativar/inativar perguntas e respostas',
  welcome_users_actions: ' enviar e-mail de ativacao,bloquear,desbloquear app users',
  welcome_admin_actions: 'gerenciar usuários administrativos',
  welcome_users_registered: 'usuários inscritos',
  welcome_menu_location: 'menu superior direito',
  welcome_tool: 'Esta é sua ferramenta administrativa. Você pode ',
  welcome_description: ' que serão as preferências para os app users. Os usuários irão responder estas perguntas no momento do cadastro no app e nos usamos estas respostas para ajudar os usuários a encontrar sua alma gêmea , portanto estas perguntas e repostas são muito importante. Você também pode ver os ',
  welcome_also: ' através dessa ferramenta e você também pode ',
  welcome_youcan: ' você pode ',
  welcome_please: 'Por favor use o ',
  welcome_access: ' para ter acesso a estas funcionalidades.',
  menu_users: 'Usuários',
  menu_qa: 'Perguntas',
  menu_language: 'Idioma',
  menu_users_app: 'Usuarios do app',
  menu_users_admin: 'Usuarios admin',
  menu_users_dash: 'Dashboard',
  menu_qa_categories: 'Categorias',
  menu_qa_questions: 'Perguntas',
  menu_qa_quiz: 'Questionário',
  menu_language_pt: 'Português',
  menu_language_en: 'Inglês',
  menu_language_fr: 'Francês',
  menu_language_sp: 'Espanhol',
  menu_profile: 'Perfil',
  menu_logout: 'Sair',
  commons_addnew: 'Adicionar Novo',  
  commons_filter: 'Filtrar',  
  commons_all: 'Todos',  
  commons_inactive: 'Inativos',  
  commons_active: 'Ativos', 
  commons_search: 'Pesquisar',  
  commons_searchfailed: 'Pesquisa falhou',
  commons_searchfor: 'Pesquisar por',
  commons_transactionfailed: 'Transação falhou',
  commons_delete: 'Excluir',
  commons_activate: 'Ativar',
  commons_update: 'Atualizar',
  commons_areyousure: "Você esta certo sobre esta execução?",
  commons_confirmexclusion: "Confirmação para exclusão",
  commons_confirmactivation: "Confirmação para ativar",
  commons_yes: 'SIM',
  commons_ok: 'OK',
  commons_sucess: 'Sucesso',  
  commons_activatedsuccess: "foi ativada com sucesso",
  commons_createdsuccess: "foi criada com sucesso",
  commons_updatedsuccess: "foi atualizada com sucesso",
  commons_deletedsuccess: "foi deletada com sucesso",
  commons_create: "Criar",
  category_createcategory:'Criar uma nova categoria',
  category_msgdel1: "A categoria",
  category_msgdel2: "tem",
  category_msgdel3: "pergunta(s) e todas elas serão excluidas.",  
  category_msgact3: " question(s) and all of them will be activated.",     
  category_namerequired: 'Nome da categoria é obrigatória',
  category_minlength: 'Nome da categorida deve ter no minimo 4 characteres',
  category_name: 'Nome da categoria',
  category_title: 'categorias',
  category_labels :  ['id','categoria','ativo','perguntas','criador','data atualizacao'],
  category_editcategory: "Editar categoria",
  

};