export const languageFR = {
    welcome_welcome: 'Bienvenue',
    welcome_questions_actions: 'enregistrer / activer / désactiver les questions et réponses',
    welcome_users_actions: "envoyer un e-mail d'activation, bloquer, débloquer les utilisateurs de l'application",
    welcome_admin_actions: 'gérer les utilisateurs administratifs',
    welcome_users_registered: 'utilisateurs abonnés',
    welcome_menu_location: 'menu en haut à droite',
    welcome_tool: 'Ceci est votre outil administratif. Vous pouvez ',
    welcome_description: "qui seront les préférences des utilisateurs de l'application. Les utilisateurs répondront à ces questions lors de l'inscription sur l'application et nous utilisons ces réponses pour aider les utilisateurs à trouver leur âme sœur, ces questions et réponses sont donc très importantes. Vous pouvez également voir le ",
    welcome_also: 'grâce à cet outil et vous pouvez aussi',
    welcome_youcan: 'vous pouvez',
    welcome_please: 'Veuillez utiliser',
    welcome_access: 'pour accéder à ces fonctionnalités.',
    menu_users: 'Utilisateurs',
    menu_qa: 'Questions',
    menu_language: 'Langue',
    menu_users_app: "Utilisateurs de l'application",
    menu_users_admin: 'Utilisateurs administrateurs',
    menu_users_dash: "Panneau d'administration",
    menu_qa_categories: 'Catégories',
    menu_qa_questions: 'Questions',
    menu_qa_quiz: 'Quiz',
    menu_language_pt: 'Português',
    menu_language_en: 'Anglais',
    menu_language_fr: 'Français',
    menu_language_sp: 'Espagnol',
    menu_profile: 'Profil',
    menu_logout: 'Quitter',
    commons_addnew: 'Ajouter nouveau',
    commons_filter: 'Filtre',
    commons_all: 'Tout le monde',
    commons_inactive: 'Inactif',
    commons_active: 'Actifs',
    commons_search: 'Rechercher',
    commons_searchfailed: 'La recherche a échoué',
    commons_searchfor: 'Rechercher',
    commons_transactionfailed: 'La transaction a échoué',
    commons_delete: 'Supprimer',
    commons_edit: 'Modifier',
    commons_activate: 'Activer',
    commons_update: 'Mettre à jour',
    commons_updated: 'Mis à jour',
    commons_audit: 'Audit',
    commons_unblock: 'Déverrouiller',
    commons_areyousure: "Etes-vous sûr de cette exécution?",
    commons_confirmexclusion: "Confirmation de suppression",
    commons_confirmactivation: "Confirmation d'activation",
    commons_confirmasendemail: "Confirmation d'envoi d'un e-mail",
    commons_withsuccess: 'avec succès',
    commons_send: 'Soumettre',
    commons_yes: 'OUI',
    commons_ok: 'OK',
    commons_sucess: 'Succès',
    commons_activatedsuccess: "a été activé / activé avec succès",
    commons_createdsuccess: "a été créé / créé avec succès",
    commons_addedsuccess: "a été ajouté / ajouté avec succès",
    commons_updatedsuccess: "a été mis à jour / mis à jour avec succès",
    commons_deletedsuccess: "a été supprimé / supprimé avec succès",
    commons_unblockedsuccess: 'a été déverrouillé / déverrouillé avec succès',
    commons_willbeactivated: 'sera activé / activé',
    commons_willbeunblocked: 'sera déverrouillé / déverrouillé',
    commons_willreceiveactivationmail: "vous recevrez un email d'activation",
    commons_create: "Créer",
    commons_listof: "Liste de",
    commons_actions: "ACTIONS",
    commons_back: 'Retour',
    commons_close: 'Fermer',
    commons_weight: 'Peso',
    commons_answer: 'Réponse',
    commons_of: 'de',
    commons_next: 'Suivant',
    commons_previous: 'Précédent',
    commons_validationerror: 'Erreur de validation',
    commons_filloutallfields: 'Veuillez remplir tous les champs de commande.',
    commons_recordswithsuccess: 'enregistrement (s) réussi.',
    category_createcategory: 'Créer une nouvelle catégorie',
    category_msgdel1: "La catégorie",
    category_msgdel2: "a",
    category_msgdel3: "question (s) et elles seront toutes supprimées.",
    category_msgact3: "question (s) et elles seront toutes activées.",
    category_namerequired: 'Le nom de la catégorie est requis',
    category_minlength: 'Le nom de la catégorie doit comporter au moins 4 caractères',
    nom_catégorie: 'Nom de la catégorie',
    category_title: 'catégories',
    category_labels: ['id', 'category', 'active', 'questions', 'creator', 'updated at'],
    category_editcategory: "Modifier la catégorie",
    audit_labels: ['PK', 'mis à jour par', 'modifié par', 'colonne', 'ancienne valeur', 'nouvelle valeur'],
    quiz_labels: ['ordre', 'catégorie', 'question', 'poids', 'n réponses', 'réponses'],
    quiz_title: 'Ordre des questions',
    quiz_save: 'Enregistrer la commande',
    quiz_preview: 'Aperçu',
    quiz_preview_title: "Utilisateurs de l'application Préférences - aperçu",
    question_name: 'Question',
    question_msg1: 'Aucune catégorie enregistrée, veuillez en enregistrer une pour continuer',
    question_minlength: 'La question doit comporter au moins 4 caractères',
    question_selectonecategory: 'Sélectionnez une catégorie',
    question_categorymandatory: 'La catégorie est un champ obligatoire.',
    question_labels: ['id', 'category', 'question', 'active', 'weight', 'n answers', 'answers', 'créateur', 'mis à jour le'],
    question_msgdel1: "La question",
    question_msgdel2: "a",
    question_msgdel3: "réponse (s) et toutes seront supprimées.",
    question_msgact3: "réponse (s) et elles seront toutes activées.",
    question_multiplechoice: "C'est un choix multiple:",
    question_yes: 'Oui',
    question_no: 'Non',
    question_selectweight: 'Sélectionnez un poids',
    question_answers: 'Answers',
    question_addanswers: 'Ajouter une réponse',
    question_savequestion: 'Enregistrer la question',
    question_required: 'La question est obligatoire',
    question_multiplechoicerequired: 'Le champ à choix multiple est obligatoire',
    question_weightrequired: 'Un poids est requis',
    question_answeresrequired: "Des réponses sont requises",
    question_answeresminimum: 'La question doit avoir au moins 2 réponses',
    question_create: 'Créer une question',
    question_update: 'Mettre à jour la question',
    question_edit: 'Modifier la question',
    question_addanswer: 'Ajouter une réponse',
    answer_name: 'Answer',
    answers_labels: ['id', 'answer', 'weight', 'updated at'],
    answers_minlength: 'La réponse doit contenir au moins 3 caractères',
    answer_required: 'Une réponse est requise',
    answer_willbeexcluded: 'sera exclu / exclu',
    editcreate_question_answersLabels: ['answer', 'weight'],
    dash_chartname: 'Graphique utilisateur',
    dash_completed: 'Terminé',
    dash_pending: 'En attente',
    dash_geolocation: 'Coordonnées',
    dash_userstoday: "Aujourd'hui",
    dash_totalusers: 'total',
    dash_blocked: 'Bloqué',
    dash_inactive: 'Inactif',
    dash_unknown: 'Inconnu',
    appusers_namefield: 'Nom',
    appusers_namefieldminlength: 'Le nom doit comporter au moins 4 caractères',
    appusers_loginvalidemail: 'La connexion doit être une adresse e-mail valide',
    appusers_coluser: 'Nom',
    appusers_collogin: 'E-mail',
    appusers_colstatus: 'Statut',
    appusers_colphotos: 'Photos',
    appusers_colcompletion: 'Pourcentage',
    appusers_colaction: 'Actions',
    appuser_activeuser: "Activer l'utilisateur",
    appuser_unblockeduser: "Débloquer l'utilisateur",
    appuser_sendactivationemail: "Renvoyer l'e-mail d'activation",
    appuser_inactiveuser: "Désactiver l'utilisateur",
    appuser_detailuser: "Détails de l'utilisateur",
    appuser_auditluser: 'Audit utilisateur',
    appuser_theappuser: "L'utilisateur de l'application",
    appuser_activationmailsend: "L'e-mail d'activation a été envoyé",
    status_completed: 'Terminé',
    status_pending: "En attente",
    status_blocked: 'Bloqué',
    status_inactive: 'Inactif',
    status_unknown: 'Inconnu',
    adminuser_label: ['id', 'email', 'nom', 'super utilisateur', 'actif', 'bloqué', 'modifié dans', 'modifié par'],
    adminuser_searchforlogin: 'Rechercher des e-mails ...',
    adminuser_searchforname: 'Nom de la recherche ...',
    adminuser_loginminlength: 'La connexion doit comporter au moins 4 caractères',
    adminuser_nameminlength: "Le nom d'utilisateur doit comporter au moins 4 caractères",
    adminuser_audit: "Audit de l'utilisateur admin",
    adminuser_theadminuser: "L'utilisateur admin",
    adminuser_namefield: 'Nom',
    adminuser_loginfield: 'Login (email)',
    adminuser_issuperuser: 'Êtes-vous un super utilisateur?',
    adminuser_permissions: 'Autorisations',
    adminuser_superuserrequired: 'Choisir si vous êtes un super utilisateur est obligatoire',
    adminuser_namerequired: 'Le nom est requis',
    adminuser_checkforall: 'Cocher pour tout sélectionner',
    adminuser_uncheckforall: 'Décocher pour tout désélectionner',
    adminuser_createadminuser: 'Créer un utilisateur administrateur',
    adminuser_saveuser: "Enregistrer l'utilisateur",
    adminuser_edituser: "Modifier l'utilisateur admin",
    detailuser_personaldata: 'Données personnelles',
    detailuser_address: 'Adresse',
    detailuser_photo: 'Photo (s)',
    detailuser_preferences: 'Préférences',
    detailuser_personaldata_name: 'Nom',
    detailuser_personaldata_login: 'Connexion (email)',
    detailuser_personaldata_birthdate: 'Anniversaire',
    detailuser_personaldata_gender: 'Sexe',
    detailuser_personaldata_occupation: 'Profession',
    detailuser_personaldata_educationlevel: 'Scolarité',
    detailuser_personaldata_maritalstatus: 'État matrimonial',
    detailuser_personaldata_mobilenumber: 'Mobile',
    detailuser_address_address: 'Adresse',
    detailuser_address_addressline2: 'Complément',
    detailuser_address_district: 'Quartier',
    detailuser_address_city: 'Ville',
    detailuser_address_state: 'Statut',
    detailuser_address_postalcode: 'Cep',
    sign_aries: 'Bélier',
    sign_taurus: 'Taureau',
    sign_gemini: 'Gémeaux',
    sign_cancer: 'Cancer',
    sign_leo: 'Leo',
    sign_virgo: 'Vierge',
    sign_libra: 'Balance',
    sign_scorpio: 'Scorpion',
    sign_sagittarius: 'Sagittaire',
    sign_capricorn: 'Capricorne',
    sign_aquarius: 'Verseau',
    sign_pisces: 'Poissons',
    profile_page: 'Profil',
    profile_update: 'Mettre à jour le profil',
    profile_permissions: 'Autorisations',
    profile_loginrequired: 'Une connexion est requise',
    profile_weakpassword: 'Mot de passe faible',
    profile_newpassword: 'nouveau mot de passe',
    profile_passwordminlength: 'Le mot de passe doit contenir au moins 8 caractères',
    profile_passwordinfo0: 'Le mot de passe doit avoir ...',
    profile_passwordinfo1: 'au moins 1 chiffre',
    profile_passwordinfo2: 'au moins 1 caractère spécial',
    profile_passwordinfo3: 'au moins 1 lettre majuscule',
    profile_passwordinfo4: 'au moins 1 lettre minuscule',
    profile_passwordinfo5: 'minimum 8 caractères',
    profile_updatedsucess: "votre profil a été mis à jour avec succès",
    login_2youraccount: 'Connectez-vous à votre compte',
    login_forgotpassword: 'Mot de passe oublié',
    login_passwordrequired: 'Le mot de passe est requis',
    login_emailrequired: 'E-mail est requis',
    login_emailvalid: "L'e-mail doit être un e-mail valide",
    login_password: 'Mot de passe',
    login_login: 'Connexion',
    forgotpassword_submit: 'Soumettre',
    forgotpassword_loginpage: 'Page de connexion',
    forgotpassword_accountreset: 'le compte a été réinitialisé',
    forgotpassword_instructionssend: 'Un e-mail a été envoyé avec des instructions pour un nouvel accès',
    httpserviceunavailable: "API  indisponible",
    permission_list_category: 'Liste des catégories',
    permission_create_category: 'Créer une catégorie',
    permission_activate_category: 'Activer la catégorie',
    permission_inactivate_category: 'Désactiver la catégorie',
    permission_update_category: 'Modifier la catégorie',
    permission_list_question: 'Répertorier les questions',
    permission_create_question: 'Créer une question',
    permission_activate_question: 'Activer la question',
    permission_inactivate_question: 'Désactiver la question',
    permission_update_question: 'Modifier la question',
    permission_order_quiz: 'Questions posées',
    permission_preview_quiz: 'Aperçu du questionnaire',
    permission_list_adminUser: 'Répertorier les utilisateurs admin',
    permission_create_adminUser: 'Créer des utilisateurs administrateurs',
    permission_update_adminUser: 'Modifier les utilisateurs admin',
    permission_inactivate_adminUser: 'Désactiver les utilisateurs admin',
    permission_activate_adminUser: 'Activer les utilisateurs admin',
    permission_unblocked_adminUser: 'Débloquer les utilisateurs admin',
    permission_list_appUser: "Répertorier les utilisateurs de l'application",
    permission_detail_appUser: "Détaillez les utilisateurs de l'application",
    permission_inactivate_appUser: "Désactiver les utilisateurs de l'application",
    permission_activate_appUser: "Activer les utilisateurs de l'application",
    permission_unblocked_appUser: "Débloquer les utilisateurs de l'application",
    permission_dashboard: "Panneau d'administration",    
    preview_info1: "Sur cette page, vous pouvez spécifier les questions qui seront affichées à l'utilisateur lors de l'enregistrement de l'application.",
    preview_info2: 'Cliquez simplement sur les boutons suivant et précédent pour voir les questions, elles ne recevront pas de réponse car elles sont uniquement destinées à la visualisation.',
  };