export const languageEN = {
    welcome_welcome: 'Welcome',
    welcome_questions_actions: 'register/activate/inactivate questions',
    welcome_users_actions: ' send activation email,block,unblock app users',
    welcome_admin_actions: 'manage administrative users',
    welcome_users_registered: 'users registered',
    welcome_menu_location: 'right top menu',
    welcome_tool: 'This is your admin tool. You can ',
    welcome_description: ' which will be the preferences for app users who will respond those questions when they subscribe on app and we use this answers to help them to find a match, so those questions are very important. You also can see the app  ',
    welcome_also: ' through this tool and you can ',
    welcome_please: 'Please access the ',
    welcome_youcan: ' you can',
    welcome_access: ' for access these features',
    menu_users: 'Users',
    menu_qa: 'Q&A',
    menu_language: 'Language',
    menu_users_app: 'App Users',
    menu_users_admin: 'Admin Users',
    menu_users_dash: 'Dashboard',
    menu_qa_categories: 'Categories',
    menu_qa_questions: 'Questions',
    menu_qa_quiz: 'Quiz',
    menu_language_pt: 'Portuguese',
    menu_language_en: 'English',
    menu_language_fr: 'French',
    menu_language_sp: 'Spanish',
    menu_profile: 'Profile',
    menu_logout: 'Logout',
    commons_addnew: 'Add New',  
    commons_filter: 'Filter',  
    commons_all: 'All',  
    commons_inactive: 'Inactive',  
    commons_active: 'Active', 
    commons_search: 'Search',  
    commons_searchfailed: 'Search failed',
    commons_searchfor: 'Search for',
    commons_transactionfailed: 'Transaction failed',
    commons_delete: 'Delete',
    commons_edit: 'Edit',
    commons_update: 'Update',
    commons_activate: 'Activate',
    commons_audit: 'Audit',
    commons_areyousure: "Are you totally sure about this operation?",
    commons_confirmexclusion: "Confirmation for exclusion",
    commons_confirmactivation: "Confirmation for activation",
    commons_yes: 'YES',
    commons_ok: 'OK',
    commons_sucess: 'Success',
    commons_activatedsuccess: "was activated with sucess",
    commons_createdsuccess: "was created with sucess",
    commons_updatedsuccess: "was updated with sucess",
    commons_deletedsuccess: "was deleted with sucess",
    commons_create: "Create",
    commons_listof: "List of",
    commons_actions: "ACTIONS",
    commons_back: 'Back',
    commons_close: 'Close',
    category_createcategory:'Create a new category',
    category_msgdel1: "The category",
    category_msgdel2: "has ",
    category_msgdel3: " question(s) and all of them will be excluded.", 
    category_msgact3: " question(s) and all of them will be activated.",     
    category_namerequired: 'Category name is required',
    category_minlength: 'Category name must be at least 4 characters',
    category_name: 'Category name',
    category_title: 'categories',
    category_labels :  ['id','category','active','questions','owner','update date'],
    category_editcategory: "Edit category",
    audit_labels: ['PK','update date','changed by','column','old value','new value'],
    quiz_labels: ['order','category','name of question','weigth','n answers','answers'],
    quiz_title: 'Quiz Order',
    quiz_save: 'Save Quiz',
    quiz_preview: 'Preview',
    question_msg1: 'There is no active category registered, please register one first',
    question_minlength: 'Question name must be at least 4 characters',
    question_selectonecategory: 'Select one category',
    question_labels: ['id','category','name of question','act','wt','multiple','ans','owner','update date'],
    question_msgdel1: "The question",
    question_msgdel2: "has ",
    question_msgdel3: " answer(s) and all of them will be excluded.", 
    question_msgact3: " answer(s) and all of them will be activated.",   
    answers_labels: ['id','answer','weight','lastUpdateDate'],

  };