export const languageEN = {
    welcome_welcome: 'Welcome',
    welcome_questions_actions: 'register/activate/inactivate questions',
    welcome_users_actions: ' send activation email,block,unblock app users',
    welcome_admin_actions: 'manage administrative users',
    welcome_users_registered: 'users registered',
    welcome_menu_location: 'right top menu',
    welcome_tool: 'This is your admin tool. You can ',
    welcome_description: ' which will be the preferences for app users who will respond those questions when they subscribe on app and we use this answers to help them to find a match, so those questions are very important. You also can see the app  ',
    welcome_also: ' through this tool and you can ',
    welcome_please: 'Please access the ',
    welcome_youcan: ' you can',
    welcome_access: ' for access these features',
    menu_users: 'Users',
    menu_qa: 'Q&A',
    menu_language: 'Language',
    menu_users_app: 'App Users',
    menu_users_admin: 'Admin Users',
    menu_users_dash: 'Dashboard',
    menu_qa_categories: 'Categories',
    menu_qa_questions: 'Questions',
    menu_qa_quiz: 'Quiz',
    menu_language_pt: 'Portuguese',
    menu_language_en: 'English',
    menu_language_fr: 'French',
    menu_language_sp: 'Spanish',
    menu_profile: 'Profile',
    menu_logout: 'Logout',
      
  };