export const languageES = {
  welcome_welcome: 'Bienvenido',
  welcome_questions_actions: 'registrar / activar / desactivar preguntas y respuestas',
  welcome_users_actions: 'enviar correo electrónico de activación, bloquear, desbloquear usuarios de la aplicación',
  welcome_admin_actions: 'administrar usuarios administrativos',
  welcome_users_registered: 'usuarios suscritos',
  welcome_menu_location: 'menú superior derecho',
  welcome_tool: 'Esta es su herramienta administrativa. Tu puedes ',
  welcome_description: 'que serán las preferencias para los usuarios de la aplicación. Los usuarios responderán estas preguntas cuando se registren en la aplicación y usamos estas respuestas para ayudar a los usuarios a encontrar su alma gemela, por lo que estas preguntas y respuestas son muy importantes. También puede ver el ',
  welcome_also: 'a través de esta herramienta y tú también puedes',
  welcome_youcan: 'puedes',
  welcome_please: 'Por favor use',
  welcome_access: 'para acceder a estas funciones.',
  menu_users: 'Usuarios',
  menu_qa: 'Preguntas',
  menu_language: 'Idioma',
  menu_users_app: 'Usuarios de la aplicación',
  menu_users_admin: 'Usuarios administradores',
  menu_users_dash: 'Panel de administración',
  menu_qa_categories: 'Categorías',
  menu_qa_questions: 'Preguntas',
  menu_qa_quiz: 'Prueba',
  menu_language_pt: 'Português',
  menu_language_en: 'Inglés',
  menu_language_fr: 'Francés',
  menu_language_sp: 'español',
  menu_profile: 'Perfil',
  menu_logout: 'Salir',
  commons_addnew: 'Agregar nuevo',
  commons_filter: 'Filtro',
  commons_all: 'Todos',
  commons_inactive: 'Inactivo',
  commons_active: 'Activos',
  commons_search: 'Buscar',
  commons_searchfailed: 'Búsqueda fallida',
  commons_searchfor: 'Buscar',
  commons_transactionfailed: 'Transacción fallida',
  commons_delete: 'Eliminar',
  commons_edit: 'Editar',
  commons_activate: 'Habilitar',
  commons_update: 'Actualización',
  commons_updated: 'Actualizado',
  commons_audit: 'Auditoría',
  commons_unblock: 'Desbloquear',
  commons_areyousure: "¿Estás seguro de esta ejecución?",
  commons_confirmexclusion: "Confirmación de eliminación",
  commons_confirmactivation: "Confirmación para activar",
  commons_confirmasendemail: "Confirmación para enviar correo electrónico",
  commons_withsuccess: 'con éxito',
  commons_send: 'Enviar',
  commons_yes: 'SÍ',
  commons_ok: 'OK',
  commons_sucess: 'Éxito',
  commons_activatedsuccess: "se ha activado / activado con éxito",
  commons_createdsuccess: "fue creado / creado con éxito",
  commons_addedsuccess: "fue agregado / agregado exitosamente",
  commons_updatedsuccess: "se actualizó / actualizó correctamente",
  commons_deletedsuccess: "fue eliminado / eliminado correctamente",
  commons_unblockedsuccess: 'se ha desbloqueado / desbloqueado con éxito',
  commons_willbeactivated: 'será activado / activado',
  commons_willbeunblocked: 'será desbloqueado / desbloqueado',
  commons_willreceiveactivationmail: 'recibirá un correo electrónico de activación',
  commons_create: "Crear",
  commons_listof: "Lista de",
  commons_actions: "ACCIONES",
  commons_back: 'Atrás',
  commons_close: 'Cerrar',
  commons_weight: 'Peso',
  commons_answer: 'Respuesta',
  commons_of: 'de',
  commons_next: 'Siguiente',
  commons_previous: 'Anterior',
  commons_validationerror: 'Error de validación',
  commons_filloutallfields: 'Complete todos los campos del pedido.',
  commons_recordswithsuccess: 'registro (s) exitoso.',
  category_createcategory: 'Crear una nueva categoría',
  category_msgdel1: "La categoría",
  category_msgdel2: "tiene",
  category_msgdel3: "pregunta (s) y se eliminarán todas.",
  category_msgact3: "pregunta (s) y se activarán todas.",
  category_namerequired: 'El nombre de la categoría es obligatorio',
  category_minlength: 'El nombre de la categoría debe tener al menos 4 caracteres',
  category_name: 'Nombre de categoría',
  category_title: 'categorías',
  category_labels: ['id', 'categoría', 'activo', 'preguntas', 'creador', 'actualizado en'],
  category_editcategory: "Editar categoría",
  audit_labels: ['PK', 'actualizado por', 'modificado por', 'columna', 'valor antiguo', 'valor nuevo'],
  quiz_labels: ['orden', 'categoría', 'pregunta', 'peso', 'n respuestas', 'respuestas'],
  quiz_title: 'Orden de las preguntas',
  quiz_save: 'Guardar pedido',
  quiz_preview: 'Vista previa',
  quiz_preview_title: 'Usuarios de la aplicación de preferencias: vista previa',
  question_name: 'Pregunta',
  question_msg1: 'Ninguna categoría registrada, por favor registre una para continuar',
  question_minlength: 'La pregunta debe tener al menos 4 caracteres',
  question_selectonecategory: 'Seleccionar una categoría',
  question_categorymandatory: 'La categoría es un campo obligatorio.',
  question_labels: ['id', 'categoría', 'pregunta', 'activo', 'peso', 'n respuestas', 'respuestas', 'creador', 'actualizado en'],
  question_msgdel1: "La pregunta",
  question_msgdel2: "tiene",
  question_msgdel3: "respuesta (s) y todas serán eliminadas.",
  question_msgact3: "respuesta (s) y se activarán todas.",
  question_multiplechoice: 'Es opción múltiple:',
  question_yes: 'Sí',
  question_no: 'No',
  question_selectweight: 'Seleccione un peso',
  question_answers: 'Respuestas',
  question_addanswers: 'Agregar respuesta',
  question_savequestion: 'Guardar pregunta',
  question_required: 'Pregunta es obligatoria',
  question_multiplechoicerequired: 'El campo de opción múltiple es obligatorio',
  question_weightrequired: 'Se requiere peso',
  question_answeresrequired: 'Se requieren respuestas',
  question_answeresminimum: 'La pregunta debe tener al menos 2 respuestas',
  question_create: 'Crear pregunta',
  question_update: 'Actualizar pregunta',
  question_edit: 'Editar pregunta',
  question_addanswer: 'Agregar respuesta',
  answer_name: 'Respuesta',
  answer_labels: ['id', 'answer', 'weight', 'updated at'],
  answers_minlength: 'La respuesta debe tener al menos 3 caracteres',
  answer_required: 'Se requiere respuesta',
  answer_willbeexcluded: 'será excluido / excluido',
  editcreate_question_answersLabels: ['respuesta', 'peso'],
  dash_chartname: 'Gráfico de usuario',
  dash_completed: 'Completado',
  dash_pending: 'Pendiente',
  dash_geolocation: 'Coordenadas',
  dash_userstoday: 'Hoy',
  dash_totalusers: 'total',
  dash_blocked: 'Bloqueado',
  dash_inactive: 'Inactivo',
  dash_unknown: 'Desconocido',
  appusers_namefield: 'Nombre',
  appusers_namefieldminlength: 'El nombre debe tener al menos 4 caracteres',
  appusers_loginvalidemail: 'El inicio de sesión debe ser un correo electrónico válido',
  appusers_coluser: 'Nombre',
  appusers_collogin: 'Correo electrónico',
  appusers_colstatus: 'Estado',
  appusers_colphotos: 'Fotos',
  appusers_colcompletion: 'Porcentaje',
  appusers_colaction: 'Acciones',
  appuser_activeuser: 'Habilitar usuario',
  appuser_unblockeduser: 'Desbloquear usuario',
  appuser_sendactivationemail: 'Reenviar correo electrónico de activación',
  appuser_inactiveuser: 'Desactivar usuario',
  appuser_detailuser: 'Usuario detallado',
  appuser_auditluser: 'Auditar usuario',
  appuser_theappuser: 'El usuario de la aplicación',
  appuser_activationmailsend: 'Se ha enviado el correo electrónico de activación',
  status_completed: 'Completo',
  status_pending: 'Pendiente',
  status_blocked: 'Bloqueado',
  status_inactive: 'Inactivo',
  status_unknown: 'Desconocido',
  adminuser_label: ['id', 'email', 'nombre', 'superusuario', 'activo', 'bloqueado', 'modificado en', 'modificado por'],
  adminuser_searchforlogin: 'Buscar correo electrónico ...',
  adminuser_searchforname: 'Nombre de búsqueda ...',
  adminuser_loginminlength: 'El inicio de sesión debe tener al menos 4 caracteres',
  adminuser_nameminlength: 'El nombre de usuario debe tener al menos 4 caracteres',
  adminuser_audit: 'Auditando el administrador del usuario',
  adminuser_theadminuser: 'El usuario administrador',
  adminuser_namefield: 'Nombre',
  adminuser_loginfield: 'Iniciar sesión (correo electrónico)',
  adminuser_issuperuser: '¿Eres un superusuario?',
  adminuser_permissions: 'Permisos',
  adminuser_superuserrequired: 'Elegir si eres un superusuario es obligatorio',
  adminuser_namerequired: 'El nombre es obligatorio',
  adminuser_checkforall: 'Marque para seleccionar todo',
  adminuser_uncheckforall: 'Desmarque para deseleccionar todo',
  adminuser_createadminuser: 'Crear usuario administrador',
  adminuser_saveuser: 'Guardar usuario',
  adminuser_edituser: 'Editar usuario administrador',
  detailuser_personaldata: 'Datos personales',
  detailuser_address: 'Dirección',
  detailuser_photo: 'Foto (s)',
  detailuser_preferences: 'Preferencias',
  detailuser_personaldata_name: 'Nombre',
  detailuser_personaldata_login: 'Iniciar sesión (correo electrónico)',
  detailuser_personaldata_birthdate: 'Cumpleaños',
  detailuser_personaldata_gender: 'Sexo',
  detailuser_personaldata_occupation: 'Profesión',
  detailuser_personaldata_educationlevel: 'Escolaridad',
  detailuser_personaldata_maritalstatus: 'Estado civil',
  detailuser_personaldata_mobilenumber: 'Móvil',
  detailuser_address_address: 'Dirección',
  detailuser_address_addressline2: 'Complemento',
  detailuser_address_district: 'Barrio',
  detailuser_address_city: 'Ciudad',
  detailuser_address_state: 'Estado',
  detailuser_address_postalcode: 'Cep',
  sign_aries: 'Aries',
  sign_taurus: 'Tauro',
  sign_gemini: 'Géminis',
  sign_cancer: 'Cáncer',
  sign_leo: 'Leo',
  sign_virgo: 'Virgo',
  sign_libra: 'Libra',
  sign_scorpio: 'Escorpio',
  sign_sagittarius: 'Sagitario',
  sign_capricorn: 'Capricornio',
  sign_aquarius: 'Acuario',
  sign_pisces: 'Piscis',
  profile_page: 'Perfil',
  profile_update: 'Actualizar perfil',
  profile_permissions: 'Permisos',
  profile_loginrequired: 'Se requiere iniciar sesión',
  profile_weakpassword: 'Contraseña débil',
  profile_passwordminlength: 'La contraseña debe tener al menos 8 caracteres',
  profile_passwordinfo0: 'La contraseña debe tener ...',
  profile_passwordinfo1: 'al menos 1 número',
  profile_passwordinfo2: 'al menos 1 carácter especial',
  profile_passwordinfo3: 'al menos 1 letra mayúscula',
  profile_passwordinfo4: 'al menos 1 letra minúscula',
  profile_passwordinfo5: 'mínimo 8 caracteres',
  profile_updatedsucess: 'su perfil se ha actualizado correctamente',
  login_2youraccount: 'Inicie sesión en su cuenta',
  login_forgotpassword: 'Olvidó su contraseña',
  login_passwordrequired: 'Se requiere contraseña',
  login_emailrequired: 'El correo electrónico es obligatorio',
  login_emailvalid: 'El correo electrónico debe ser válido',
  login_password: 'Contraseña',
  login_login: 'Iniciar sesión',
  forgotpassword_submit: 'Enviar',
  forgotpassword_loginpage: 'Página de inicio de sesión',  
  forgotpassword_accountreset: 'la cuenta ha sido restablecida',
  forgotpassword_instructionssend: 'Se envió un correo electrónico con instrucciones para un nuevo acceso',
};