export const languagePT = {
  welcome_welcome: 'Bem vindo',
  welcome_questions_actions: 'cadastrar/ativar/inativar perguntas e respostas',
  welcome_users_actions: ' enviar e-mail de ativacao,bloquear,desbloquear app users',
  welcome_admin_actions: 'gerenciar usuários administrativos',
  welcome_users_registered: 'usuários inscritos',
  welcome_menu_location: 'menu superior direito',
  welcome_tool: 'Esta é sua ferramenta administrativa. Você pode ',
  welcome_description: ' que serão as preferências para os app users. Os usuários irão responder estas perguntas no momento do cadastro no app e nos usamos estas respostas para ajudar os usuários a encontrar sua alma gêmea , portanto estas perguntas e repostas são muito importante. Você também pode ver os ',
  welcome_also: ' através dessa ferramenta e você também pode ',
  welcome_youcan: ' você pode ',
  welcome_please: 'Por favor use o ',
  welcome_access: ' para ter acesso a estas funcionalidades.',
  menu_users: 'Usuários',
  menu_qa: 'Perguntas',
  menu_language: 'Idioma',
  menu_users_app: 'Usuarios do app',
  menu_users_admin: 'Usuarios admin',
  menu_users_dash: 'Dashboard',
  menu_qa_categories: 'Categorias',
  menu_qa_questions: 'Perguntas',
  menu_qa_quiz: 'Questionário',
  menu_language_pt: 'Português',
  menu_language_en: 'Inglês',
  menu_language_fr: 'Francês',
  menu_language_sp: 'Espanhol',
  menu_profile: 'Perfil',
  menu_logout: 'Sair',
  commons_addnew: 'Adicionar Novo',  
  commons_filter: 'Filtrar',  
  commons_all: 'Todos',  
  commons_inactive: 'Inativos',  
  commons_active: 'Ativos', 
  commons_search: 'Pesquisar',  
  commons_searchfailed: 'Pesquisa falhou',
  commons_searchfor: 'Pesquisar por',
  commons_transactionfailed: 'Transação falhou',
  commons_delete: 'Excluir',
  commons_edit: 'Editar',
  commons_activate: 'Ativar',
  commons_update: 'Atualizar',
  commons_updated: 'Atualizado',
  commons_audit: 'Auditoria',
  commons_areyousure: "Você esta certo sobre esta execução?",
  commons_confirmexclusion: "Confirmação para exclusão",
  commons_confirmactivation: "Confirmação para ativar",
  commons_yes: 'SIM',
  commons_ok: 'OK',
  commons_sucess: 'Sucesso',  
  commons_activatedsuccess: "foi ativada com sucesso",
  commons_createdsuccess: "foi criada com sucesso",
  commons_addedsuccess: " foi  adicionada com sucesso",
  commons_updatedsuccess: "foi atualizada com sucesso",
  commons_deletedsuccess: "foi deletada com sucesso",
  commons_create: "Criar",
  commons_listof: "Lista de",
  commons_actions: "AÇÕES",  
  commons_back: 'Voltar',
  commons_close: 'Fechar',
  commons_weight: 'Peso',
  commons_answer: 'Resposta',
  commons_of: 'de',
  commons_next: 'Proximo',
  commons_previous: 'Anterior',
  commons_validationerror: 'Erro de validação',
  commons_filloutallfields: 'Por favor, preencha todos os campos de ordenação.',   
  commons_recordswithsuccess: ' registro(s) com sucesso.',
  category_createcategory:'Criar uma nova categoria',
  category_msgdel1: "A categoria",
  category_msgdel2: "tem",
  category_msgdel3: "pergunta(s) e todas elas serão excluidas.",  
  category_msgact3: " pergunta(s) e todas elas serão ativadas.",     
  category_namerequired: 'Nome da categoria é obrigatória',
  category_minlength: 'Nome da categorida deve ter no minimo 4 caracteres',
  category_name: 'Nome da categoria',
  category_title: 'categorias',
  category_labels :  ['id','categoria','ativo','perguntas','criador','atualizado em'],
  category_editcategory: "Editar categoria",
  audit_labels: ['PK','atualizado em','modificado por','coluna','valor antigo','novo valor'],  
  quiz_labels: ['ordem','categoria','pergunta','peso','n respostas','respostas'],
  quiz_title: 'Ordem das Perguntas',
  quiz_save: 'Salvar Ordem',
  quiz_preview: 'PreVisualizar',
  quiz_preview_title: 'Preferências app users - previsualizar',
  question_name: 'Pergunta',
  question_msg1: 'Sem categoria registrada, por favor cadastre uma para continuar',
  question_minlength: 'A pergunta deve ter no minimo 4 caracteres',
  question_selectonecategory: 'Selecione uma categoria',
  question_categorymandatory: 'Categoria é um campo obrigatório.',
  question_labels: ['id','categoria','pergunta','ativo','peso','n respostas','respostas','criador','atualizado em'],
  question_msgdel1: "A pergunta",
  question_msgdel2: "tem",
  question_msgdel3: " resposta(s) e todas elas serão excluidas.", 
  question_msgact3: " resposta(s) e todas elas serão ativadas.",  
  question_multiplechoice: 'É multipla escolha:',
  question_yes: 'Sim',
  question_no: 'Não',
  question_selectweight: 'Selecione um peso',
  question_answers: 'Respostas',
  question_addanswers: 'Adiciona resposta',
  question_savequestion: 'Salvar Pergunta',
  question_required: 'Pergunta é obrigatório',
  question_multiplechoicerequired: 'Campo multipla escolha é obrigatório',
  question_weightrequired: 'Peso é obrigatório',
  question_answeresrequired: 'Respostas é obrigatório',
  question_answeresminimum: 'Pergunta deve ter pelo menos 2 repostas',
  question_create: 'Criar Pergunta',
  question_update: 'Atualizar Pergunta',
  question_edit: 'Editar Pergunta',
  question_addanswer: 'Adicionar resposta',
  answer_name: 'Resposta',
  answers_labels: ['id','resposta','peso','atualizado em'],   
  answers_minlength: 'Resposta deve ter no minimo 3 caracteres',
  answer_required: 'Resposta é obrigatório',
  answer_willbeexcluded: 'será excluida',
  editcreate_question_answersLabels: ['resposta','peso'],
};