export const languageEN = {
    welcome_welcome: 'Welcome',
    welcome_questions_actions: 'register/activate/inactivate questions',
    welcome_users_actions: ' send activation email,block,unblock app users',
    welcome_admin_actions: 'manage administrative users',
    welcome_users_registered: 'users registered',
    welcome_menu_location: 'right top menu',
    welcome_tool: 'This is your admin tool. You can ',
    welcome_description: ' which will be the preferences for app users who will respond those questions when they subscribe on app and we use this answers to help them to find a match, so those questions are very important. You also can see the app  ',
    welcome_also: ' through this tool and you can ',
    welcome_please: 'Please access the ',
    welcome_youcan: ' you can',
    welcome_access: ' for access these features',
    menu_users: 'Users',
    menu_qa: 'Q&A',
    menu_language: 'Language',
    menu_users_app: 'App Users',
    menu_users_admin: 'Admin Users',
    menu_users_dash: 'Dashboard',
    menu_qa_categories: 'Categories',
    menu_qa_questions: 'Questions',
    menu_qa_quiz: 'Quiz',
    menu_language_pt: 'Portuguese',
    menu_language_en: 'English',
    menu_language_fr: 'French',
    menu_language_sp: 'Spanish',
    menu_profile: 'Profile',
    menu_logout: 'Logout',
    commons_addnew: 'Add New',  
    commons_filter: 'Filter',  
    commons_all: 'All',  
    commons_inactive: 'Inactive',  
    commons_active: 'Active', 
    commons_search: 'Search',  
    commons_searchfailed: 'Search failed',
    commons_searchfor: 'Search for',
    commons_transactionfailed: 'Transaction failed',
    commons_delete: 'Delete',
    commons_edit: 'Edit',
    commons_update: 'Update',
    commons_updated: 'Updated',
    commons_activate: 'Activate',
    commons_audit: 'Audit',
    commons_unblock: 'Unblock',
    commons_areyousure: "Are you totally sure about this operation?",
    commons_confirmexclusion: "Confirmation for exclusion",
    commons_confirmactivation: "Confirmation for activation",
    commons_confirmasendemail: "Confirmation for sending e-mail",
    commons_withsuccess: 'with success',
    commons_send: 'Send',
    commons_yes: 'YES',
    commons_ok: 'OK',
    commons_sucess: 'Success',
    commons_activatedsuccess: "was activated with sucess",
    commons_createdsuccess: "was created with sucess",
    commons_addedsuccess: "was added with sucess",
    commons_updatedsuccess: "was updated with sucess",
    commons_deletedsuccess: "was deleted with sucess",
    commons_unblockedsuccess: 'was unblocked with sucess',
    commons_willbeactivated: 'will be activated',
    commons_willbeunblocked: 'will be unblocked',
    commons_willreceiveactivationmail: 'will receive an activation e-mail',
    commons_create: "Create",
    commons_listof: "List of",
    commons_actions: "ACTIONS",
    commons_back: 'Back',
    commons_close: 'Close',
    commons_weight: 'Weight',
    commons_answer: 'Answer',
    commons_of: 'of',
    commons_next: 'Next',
    commons_previous: 'Previous',   
    commons_validationerror: 'Validation error',
    commons_filloutallfields: 'Please fill out all order fields.', 
    commons_recordswithsuccess: ' record(s) with sucess.',
    category_createcategory:'Create a new category',
    category_msgdel1: "The category",
    category_msgdel2: "has ",
    category_msgdel3: " question(s) and all of them will be excluded.", 
    category_msgact3: " question(s) and all of them will be activated.",     
    category_namerequired: 'Category name is required',
    category_minlength: 'Category name must be at least 4 characters',
    category_name: 'Category name',
    category_title: 'categories',
    category_labels :  ['id','category','active','questions','owner','update date'],
    category_editcategory: "Edit category",
    audit_labels: ['PK','update date','changed by','column','old value','new value'],
    quiz_labels: ['order','category','name of question','weigth','n answers','answers'],
    quiz_title: 'Quiz Order',
    quiz_save: 'Save Quiz',
    quiz_preview: 'Preview',
    quiz_preview_title: 'Quiz Preview',
    question_name: 'Question',
    question_msg1: 'There is no active category registered, please register one first',
    question_minlength: 'Question name must be at least 4 characters',
    question_selectonecategory: 'Select one category',
    question_categorymandatory: 'Category is a mandatory field',
    question_labels: ['id','category','name of question','act','wt','multiple','ans','owner','update date'],
    question_msgdel1: "The question",
    question_msgdel2: "has ",
    question_msgdel3: " answer(s) and all of them will be excluded.", 
    question_msgact3: " answer(s) and all of them will be activated.",   
    question_multiplechoice: 'Is Multiple Choice:',
    question_yes: 'Yes',
    question_no: 'No',
    question_selectweight: 'Select a weight',
    question_answers: 'Answers',
    question_addanswers: 'Add Answer',
    question_savequestion: 'Save Question',
    question_required: 'Question is required',
    question_multiplechoicerequired: 'MultipleChoice is required',
    question_weightrequired: 'Weight is required',
    question_answeresrequired: 'Answers is required',
    question_answeresminimum: 'Question must have at least 2 answers',
    question_create: 'Create Question',
    question_update: 'Update Question',
    question_edit: 'Edit Question',
    question_addanswer: 'Add a answer',
    answer_name: 'Answer',
    answers_labels: ['id','answer','weight','lastUpdateDate'],
    answers_minlength: 'Answer must be at least 3 characters',
    answer_required: 'Answer is required',
    answer_willbeexcluded: 'will be excluded',
    editcreate_question_answersLabels: ['answer','weight'],
    dash_chartname: 'Users Chart',
    dash_completed: 'Completed',
    dash_pending: 'Pending',
    dash_geolocation: 'Geolocation',
    dash_userstoday: 'Users today',
    dash_totalusers: 'total users',
    dash_blocked: 'Blocked',
    dash_inactive: 'Inactive',
    dash_unknown: 'Unknown',
    appusers_namefield: 'Name',
    appusers_namefieldminlength: 'Name must be at least 4 characters',
    appusers_loginvalidemail: 'Login must be a valid e-mail',
    appusers_coluser: 'Users',
    appusers_collogin: 'Login',
    appusers_colstatus: 'Status',
    appusers_colphotos: 'Photos',
    appusers_colcompletion: 'Completion',
    appusers_colaction: 'Action',
    appuser_activeuser: 'Active user',
    appuser_unblockeduser: 'Unblocked user',
    appuser_sendactivationemail: 'Send activation email',
    appuser_inactiveuser: 'Inactive user',
    appuser_detailuser: 'Detail user',
    appuser_auditluser: 'Audit user',
    appuser_theappuser: 'The app user',
    appuser_activationmailsend: 'Activation e-mail was sent',
    status_completed: 'Completed',
    status_pending: 'Pending',
    status_blocked: 'Blocked',
    status_inactive: 'Inactive',
    status_unknown: 'Unknown',
    adminuser_label: ['id','login','name','super user','active','blocked','last update','modified by'],
    adminuser_searchforlogin: 'Search for login (email)...',
    adminuser_searchforname: 'Search for name...',
    adminuser_loginminlength: 'Login must be at least 4 characters',
    adminuser_nameminlength: 'User name must be at least 4 characters',
    adminuser_audit: 'Admin User Audit',
    adminuser_theadminuser: 'The Admin user',
    adminuser_namefield: 'Name',
    adminuser_loginfield: 'Login(e-mail)',
    adminuser_issuperuser: 'Is Super User?',
    adminuser_permissions: 'Permissions',
    adminuser_superuserrequired: 'SuperUser is required',
    adminuser_namerequired: 'Name is required',
    adminuser_checkforall: 'Click for check all',
    adminuser_uncheckforall: 'Click for uncheck all',
    adminuser_createadminuser: 'Create AdminUser',
    adminuser_saveuser: 'Save User',
    adminuser_edituser: 'Edit Admin User',
    detailuser_personaldata: 'Personal Data',
    detailuser_address: 'Address',
    detailuser_photo: 'Photo(s)',
    detailuser_preferences: 'Preferences',
    detailuser_personaldata_name: 'Name',
    detailuser_personaldata_login: 'Login (e-mail)',
    detailuser_personaldata_birthdate: 'BirthDate',
    detailuser_personaldata_gender: 'Gender',
    detailuser_personaldata_occupation: 'Occupation',
    detailuser_personaldata_educationlevel: 'Education Level',
    detailuser_personaldata_maritalstatus: 'Marital Status',
    detailuser_personaldata_mobilenumber: 'Mobile Number',
    detailuser_address_address: 'Address',
    detailuser_address_addressline2: 'Address Line2',
    detailuser_address_district: 'District',
    detailuser_address_city: 'City',
    detailuser_address_state: 'State',
    detailuser_address_postalcode: 'Postal code',
    sign_aries: 'Aries',
    sign_taurus: 'Taurus',
    sign_gemini: 'Gemini',
    sign_cancer: 'Cancer',
    sign_leo: 'Leo',
    sign_virgo: 'Virgo',
    sign_libra: 'Libra',
    sign_scorpio: 'Scorpio',
    sign_sagittarius: 'Sagittarius',
    sign_capricorn: 'Capricorn',
    sign_aquarius: 'Aquarius',
    sign_pisces: 'Pisces',
    profile_page: 'Profile page',
    profile_update: 'Update Profile',
    profile_permissions: 'Permissions',
    profile_loginrequired: 'Login is required',
    profile_weakpassword: 'Weak password',
    profile_passwordminlength: 'Password must be at least 8 characters',
    profile_passwordinfo0: 'Password field should has...',
    profile_passwordinfo1: 'at least one number',
    profile_passwordinfo2: 'at least one special char',
    profile_passwordinfo3: 'at least one upper case char',
    profile_passwordinfo4: 'at least one lower case char',
    profile_passwordinfo5: 'minimum 8 chars',
    profile_updatedsucess: 'your profile was updated with sucess',
    login_2youraccount: 'Login to Your Account',
    login_forgotpassword: 'Forgot Password',
    login_passwordrequired: 'Password is required',
    login_emailrequired: 'Email is required',
    login_emailvalid: 'Email must be a valid email address',
    login_password: 'Password',
    login_login: 'Login',
    forgotpassword_submit: 'Submit',
    forgotpassword_loginpage: 'Login page',
    forgotpassword_accountreset: 'account was reset',
    forgotpassword_instructionssend: 'It was sent to you an e-mail with instructions to log in',
    httpserviceunavailable: "Http service unavailable",
    permission_list_category: 'List Category',
    permission_create_category: 'Create Category', 
    permission_activate_category: 'Activate Category',
    permission_inactivate_category: 'Inactivate Category',
    permission_update_category: 'Update Category',
    permission_list_question: 'List Question',
    permission_create_question: 'Create Question',
    permission_activate_question: 'Activate Question',
    permission_inactivate_question: 'Inactivate Question',
    permission_update_question: 'Update Question',
    permission_order_quiz: 'Order Quiz',
    permission_preview_quiz: 'Preview Quiz',
    permission_list_adminUser: 'List Admin User',
    permission_create_adminUser: 'Create Admin User',
    permission_update_adminUser: 'Update Admin User',
    permission_inactivate_adminUser: 'Inactivate Admin User',
    permission_activate_adminUser: 'Activate Admin User',
    permission_unblocked_adminUser: 'Unblocked Admin User',
    permission_list_appUser: 'List App User',
    permission_detail_appUser: 'Detail App User',
    permission_inactivate_appUser: 'Inactivate App User',
    permission_activate_appUser: 'Activate App User',
    permission_unblocked_appUser: 'Unblocked App User',
    permission_dashboard: 'Dashboard',

  };