export const languagePT = {
  welcome_welcome: 'Bem vindo',
  welcome_questions_actions: 'cadastrar/ativar/inativar perguntas e respostas',
  welcome_users_actions: ' enviar e-mail de ativacao,bloquear,desbloquear app users',
  welcome_admin_actions: 'gerenciar usuários administrativos',
  welcome_users_registered: 'usuários inscritos',
  welcome_menu_location: 'menu superior direito',
  welcome_tool: 'Esta é sua ferramenta administrativa. Você pode ',
  welcome_description: ' que serão as preferências para os app users. Os usuários irão responder estas perguntas no momento do cadastro no app e nos usamos estas respostas para ajudar os usuários a encontrar sua alma gêmea , portanto estas perguntas e repostas são muito importante. Você também pode ver os ',
  welcome_also: ' através dessa ferramenta e você também pode ',
  welcome_youcan: ' você pode ',
  welcome_please: 'Por favor use o ',
  welcome_access: ' para ter acesso a estas funcionalidades.',
  menu_users: 'Usuários',
  menu_qa: 'Perguntas',
  menu_language: 'Idioma',
  menu_users_app: 'Usuarios do app',
  menu_users_admin: 'Usuarios admin',
  menu_users_dash: 'Painel admin',
  menu_qa_categories: 'Categorias',
  menu_qa_questions: 'Perguntas',
  menu_qa_quiz: 'Questionário',
  menu_language_pt: 'Português',
  menu_language_en: 'Inglês',
  menu_language_fr: 'Francês',
  menu_language_sp: 'Espanhol',
  menu_profile: 'Perfil',
  menu_logout: 'Sair',
  commons_addnew: 'Adicionar Novo',  
  commons_filter: 'Filtrar',  
  commons_all: 'Todos',  
  commons_inactive: 'Inativos',  
  commons_active: 'Ativos', 
  commons_search: 'Pesquisar',  
  commons_searchfailed: 'Pesquisa falhou',
  commons_searchfor: 'Pesquisar por',
  commons_transactionfailed: 'Transação falhou',
  commons_delete: 'Excluir',
  commons_edit: 'Editar',
  commons_activate: 'Ativar',
  commons_update: 'Atualizar',
  commons_updated: 'Atualizado',
  commons_audit: 'Auditoria',
  commons_unblock: 'Desbloqueio',
  commons_areyousure: "Você esta certo sobre esta execução?",
  commons_confirmexclusion: "Confirmação para exclusão",
  commons_confirmactivation: "Confirmação para ativar",
  commons_confirmasendemail: "Confirmação para enviar e-mail",
  commons_withsuccess: 'with success',
  commons_send: 'Enviar',
  commons_yes: 'SIM',
  commons_ok: 'OK',
  commons_sucess: 'Sucesso',  
  commons_activatedsuccess: "foi ativada/ativado com sucesso",
  commons_createdsuccess: "foi criada/criado com sucesso",
  commons_addedsuccess: " foi  adicionada/adicionado com sucesso",
  commons_updatedsuccess: "foi atualizada/atualizado com sucesso",
  commons_deletedsuccess: "foi deletada/deleteado com sucesso",
  commons_unblockedsuccess: 'foi desbloqueado/desbloqueada com sucesso',
  commons_willbeactivated: 'será ativado/ativada',
  commons_willbeunblocked: 'será desbloqueado/desbloqueada',
  commons_willreceiveactivationmail: 'irá receber um e-mail de ativação',
  commons_create: "Criar",
  commons_listof: "Lista de",
  commons_actions: "AÇÕES",  
  commons_back: 'Voltar',
  commons_close: 'Fechar',
  commons_weight: 'Peso',
  commons_answer: 'Resposta',
  commons_of: 'de',
  commons_next: 'Proximo',
  commons_previous: 'Anterior',
  commons_validationerror: 'Erro de validação',
  commons_filloutallfields: 'Por favor, preencha todos os campos de ordenação.',   
  commons_recordswithsuccess: ' registro(s) com sucesso.',
  category_createcategory:'Criar uma nova categoria',
  category_msgdel1: "A categoria",
  category_msgdel2: "tem",
  category_msgdel3: "pergunta(s) e todas elas serão excluidas.",  
  category_msgact3: " pergunta(s) e todas elas serão ativadas.",     
  category_namerequired: 'Nome da categoria é obrigatória',
  category_minlength: 'Nome da categorida deve ter no minimo 4 caracteres',
  category_name: 'Nome da categoria',
  category_title: 'categorias',
  category_labels :  ['id','categoria','ativo','perguntas','criador','atualizado em'],
  category_editcategory: "Editar categoria",
  audit_labels: ['PK','atualizado em','modificado por','coluna','valor antigo','novo valor'],  
  quiz_labels: ['ordem','categoria','pergunta','peso','n respostas','respostas'],
  quiz_title: 'Ordem das Perguntas',
  quiz_save: 'Salvar Ordem',
  quiz_preview: 'PreVisualizar',
  quiz_preview_title: 'Preferências app users - previsualizar',
  quiz_nocategory: 'Não há nenhuma pergunta ativa registrada, por favor, registre uma primeiro.',
  question_name: 'Pergunta',
  question_msg1: 'Sem categoria registrada, por favor cadastre uma para continuar',
  question_minlength: 'A pergunta deve ter no minimo 4 caracteres',
  question_selectonecategory: 'Selecione uma categoria',
  question_categorymandatory: 'Categoria é um campo obrigatório.',
  question_labels: ['id','categoria','pergunta','ativo','peso','n respostas','respostas','criador','atualizado em'],
  question_msgdel1: "A pergunta",
  question_msgdel2: "tem",
  question_msgdel3: " resposta(s) e todas elas serão excluidas.", 
  question_msgact3: " resposta(s) e todas elas serão ativadas.",  
  question_multiplechoice: 'É multipla escolha:',
  question_yes: 'Sim',
  question_no: 'Não',
  question_selectweight: 'Selecione um peso',
  question_answers: 'Respostas',
  question_addanswers: 'Adiciona resposta',
  question_savequestion: 'Salvar Pergunta',
  question_required: 'Pergunta é obrigatório',
  question_multiplechoicerequired: 'Campo multipla escolha é obrigatório',
  question_weightrequired: 'Peso é obrigatório',
  question_answeresrequired: 'Respostas é obrigatório',
  question_answeresminimum: 'Pergunta deve ter pelo menos 2 repostas',
  question_create: 'Criar Pergunta',
  question_update: 'Atualizar Pergunta',
  question_edit: 'Editar Pergunta',
  question_addanswer: 'Adicionar resposta',
  answer_name: 'Resposta',
  answers_labels: ['id','resposta','peso','atualizado em'],   
  answers_minlength: 'Resposta deve ter no minimo 3 caracteres',
  answers_maxlength: 'Resposta maximo de 200 characters',
  answer_required: 'Resposta é obrigatório',
  answer_willbeexcluded: 'será excluida/excluido',
  editcreate_question_answersLabels: ['resposta','peso'],
  dash_chartname: 'Gráfico de usuários',
  dash_completed: 'Completos',
  dash_pending: 'Pendentes',
  dash_geolocation: 'Coordenadas',
  dash_userstoday: 'Hoje',
  dash_totalusers: 'total',
  dash_blocked: 'Bloqueados',
  dash_inactive: 'Inativos',
  dash_unknown: 'Desconhecido',
  appusers_namefield: 'Nome',
  appusers_namefieldminlength: 'Nome deve ter no minimo 4 caracteres',
  appusers_loginvalidemail: 'Login deve ser um e-mail valido',
  appusers_coluser: 'Nome',
  appusers_collogin: 'E-mail',
  appusers_colstatus: 'Status',
  appusers_colphotos: 'Fotos',
  appusers_colcompletion: 'Percentual',
  appusers_colaction: 'Ações', 
  appuser_activeuser: 'Ativar usuário',
  appuser_unblockeduser: 'Desbloquear usuário',
  appuser_sendactivationemail: 'Reenviar email de ativação',
  appuser_inactiveuser: 'Inativar usuário',  
  appuser_detailuser: 'Detalhar usuário',
  appuser_auditluser: 'Auditar usuário',
  appuser_theappuser: 'O Usuário do app',
  appuser_activationmailsend: 'E-mail de ativação foi enviado',
  status_completed: 'Completo',
  status_pending: 'Pendente',
  status_blocked: 'Bloqueado',
  status_inactive: 'Inativo',
  status_unknown: 'Desconhecido',
  adminuser_label: ['id','e-mail','nome','super usuário','ativo','bloqueado','modificado em','modificado por'],
  adminuser_searchforlogin: 'Pesquisar email...',
  adminuser_searchforname: 'Pesquisar nome...',  
  adminuser_loginminlength: 'Login deve ter no minimo 4 caracteres',
  adminuser_nameminlength: 'Nome do usuário deve ter no minimo 4 caracteres',
  adminuser_audit: 'Auditoria usuario admin',
  adminuser_theadminuser: 'O usuario admin',
  adminuser_namefield: 'Nome',
  adminuser_loginfield: 'Login(e-mail)',
  adminuser_issuperuser: 'É Super Usuário?',
  adminuser_permissions: 'Permissões',
  adminuser_superuserrequired: 'Escolher se é super usuário é obrigatório',
  adminuser_namerequired: 'Nome é obrigatório',
  adminuser_checkforall: 'Marque para selecionar todos',
  adminuser_uncheckforall: 'Desmarque para deselecionar todos',
  adminuser_createadminuser: 'Criar usuário admin',
  adminuser_saveuser: 'Salvar Usuário',
  adminuser_edituser: 'Editar usuário admin',
  detailuser_personaldata: 'Dados Pessoais',
  detailuser_address: 'Endereço',
  detailuser_photo: 'Foto(s)',
  detailuser_preferences: 'Preferências',
  detailuser_personaldata_name: 'Nome',
  detailuser_personaldata_login: 'Login (e-mail)',
  detailuser_personaldata_birthdate: 'Data de Aniversário',
  detailuser_personaldata_gender: 'Sexo',
  detailuser_personaldata_occupation: 'Profissão',
  detailuser_personaldata_educationlevel: 'Escolaridade',
  detailuser_personaldata_maritalstatus: 'Estado civil',
  detailuser_personaldata_mobilenumber: 'Celular',
  detailuser_address_address: 'Endereço',
  detailuser_address_addressline2: 'Complemento',
  detailuser_address_district: 'Bairro',
  detailuser_address_city: 'Cidade',
  detailuser_address_state: 'Estado',
  detailuser_address_postalcode: 'Cep',
  sign_aries: 'Áries',
  sign_taurus: 'Touro',
  sign_gemini: 'Gêmeos',
  sign_cancer: 'Cancer',
  sign_leo: 'Leão',
  sign_virgo: 'Virgem',
  sign_libra: 'Libra',
  sign_scorpio: 'Escorpião',
  sign_sagittarius: 'Sagitário',
  sign_capricorn: 'Capricórnio',
  sign_aquarius: 'Aquário',
  sign_pisces: 'Peixes',
  profile_page: 'Perfil',
  profile_update: 'Atualizar perfil',
  profile_permissions: 'Permissões',  
  profile_loginrequired: 'Login é obrigatório',
  profile_weakpassword: 'Senha fraca',
  profile_newpassword: 'nova senha',
  profile_passwordminlength: 'Senha deve ter no minimo 8 caracteres',
  profile_passwordinfo0: 'Senha deve ter...',
  profile_passwordinfo1: 'pelo menos 1 número',
  profile_passwordinfo2: 'pelo menos 1 caracter especial',
  profile_passwordinfo3: 'pelo menos 1 letra maiscula',
  profile_passwordinfo4: 'pelo menos 1 letra minuscula',
  profile_passwordinfo5: 'minimo 8 caracteres',  
  profile_updatedsucess: 'seu perfil foi atualizado com sucesso',
  login_2youraccount: 'Faça login na sua conta',
  login_forgotpassword: 'Esqueceu sua senha',
  login_passwordrequired: 'Senha é obrigatória',
  login_emailrequired: 'Email é obrigatório',
  login_emailvalid: 'Email deve ser um e-mail valido',
  login_password: 'Senha',
  login_login: 'Logar',
  forgotpassword_submit: 'Enviar',
  forgotpassword_loginpage: 'Página de login',
  forgotpassword_accountreset: 'conta foi redefinida',
  forgotpassword_instructionssend: 'Foi enviado um e-mail com instruções para o novo acesso',
  httpserviceunavailable: "API indisponivel",
  permission_list_category: 'Listar Categorias',
  permission_create_category: 'Criar Categoria', 
  permission_activate_category: 'Ativar Categoria',
  permission_inactivate_category: 'Inativar Categoria',
  permission_update_category: 'Editar Categoria',
  permission_list_question: 'Listar Perguntas',
  permission_create_question: 'Criar Pergunta',
  permission_activate_question: 'Ativar Pergunta',
  permission_inactivate_question: 'Inativar Pergunta',
  permission_update_question: 'Editar Pergunta',
  permission_order_quiz: 'Ordem das Perguntas',
  permission_preview_quiz: 'Previsualizar Questionário',
  permission_list_adminUser: 'Listar usuários admin',
  permission_create_adminUser: 'Criar usuários admin',
  permission_update_adminUser: 'Editar usuários admin',
  permission_inactivate_adminUser: 'Inativar usuários admin',
  permission_activate_adminUser: 'Ativar usuários admin',
  permission_unblocked_adminUser: 'Desbloquear usuários admin',
  permission_list_appUser: 'Listar usuários do app',
  permission_detail_appUser: 'Detalhar usuários do app',
  permission_inactivate_appUser: 'Inativar usuários do app',
  permission_activate_appUser: 'Ativar usuários do app',
  permission_unblocked_appUser: 'Desbloquear usuários do app',
  permission_dashboard: 'Painel administrativo',
  preview_info1: 'Nesta página você pode vertificar as perguntas que serão exibidas ao usuário no momento do registro do aplicativo.',
  preview_info2: 'Basta clicar nos botões proximo e anterior para ver as questões as mesmas não serão respondidas pois servem apenas de visualização.',
};